#**1. Import the necessary libraries**

In [ ]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, accuracy_score
from sklearn.svm import *

#**2. Load the breast dataset**

In [ ]:
data = load_breast_cancer()


#**3. Assigning the features and target**

In [ ]:
df_features = data.data
df_target = data.target
print('features data : ', df_features)
print('\ntarget data : ', df_target)

features data :  [[1.799e+01 1.038e+01 1.228e+02 ... 2.654e-01 4.601e-01 1.189e-01]
 [2.057e+01 1.777e+01 1.329e+02 ... 1.860e-01 2.750e-01 8.902e-02]
 [1.969e+01 2.125e+01 1.300e+02 ... 2.430e-01 3.613e-01 8.758e-02]
 ...
 [1.660e+01 2.808e+01 1.083e+02 ... 1.418e-01 2.218e-01 7.820e-02]
 [2.060e+01 2.933e+01 1.401e+02 ... 2.650e-01 4.087e-01 1.240e-01]
 [7.760e+00 2.454e+01 4.792e+01 ... 0.000e+00 2.871e-01 7.039e-02]]

target data :  [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 1 0 0 0 0 0 0 0 0 1 0 1 1 1 1 1 0 0 1 0 0 1 1 1 1 0 1 0 0 1 1 1 1 0 1 0 0
 1 0 1 0 0 1 1 1 0 0 1 0 0 0 1 1 1 0 1 1 0 0 1 1 1 0 0 1 1 1 1 0 1 1 0 1 1
 1 1 1 1 1 1 0 0 0 1 0 0 1 1 1 0 0 1 0 1 0 0 1 0 0 1 1 0 1 1 0 1 1 1 1 0 1
 1 1 1 1 1 1 1 1 0 1 1 1 1 0 0 1 0 1 1 0 0 1 1 0 0 1 1 1 1 0 1 1 0 0 0 1 0
 1 0 1 1 1 0 1 1 0 0 1 0 0 0 0 1 0 0 0 1 0 1 0 1 1 0 1 0 0 0 0 1 1 0 0 1 1
 1 0 1 1 1 1 1 0 0 1 1 0 1 1 0 0 1 0 1 1 1 1 0 1 1 1 1 1 0 1 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 1 1 1 1 1 1 0 1 0 1

#**4. Split the data into train and test set (with 30% test set)**

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(df_features, df_target, test_size=0.3)

#**5. Create a model SVM**
We have a classification dataset so we will use svc model

In [ ]:
model = SVC()

#**6. Fit the model to training set**

In [ ]:
model.fit(x_train, y_train)

SVC()

#**7. Predict target variable using test set**

In [ ]:
y_pred = model.predict(x_test)

#**8. Calculate accuracy and confision matrix**

In [ ]:
accur_score = accuracy_score(y_test, y_pred)
confus_matrix = confusion_matrix(y_test, y_pred)


#**9. print accuracy and accuracy**

In [ ]:
print('accuracy score : ', accur_score)
print('\nTP : ', confus_matrix[0, 0])
print('TN : ', confus_matrix[1, 1])
print('FP : ', confus_matrix[0, 1])
print('FN : ', confus_matrix[1, 0])

accuracy score :  0.9122807017543859

TP :  47
TN :  109
FP :  12
FN :  3
